#!/usr/bin/env python3
"""Build WordBurst's local family-safe dictionary bundle.

The resulting dictionary-additions.js is loaded from the same website as the game,
so mobile play never depends on a live dictionary request.
"""

from __future__ import annotations

import re
from pathlib import Path

TEXTBLOB_VERSION = "0.19.0"
ROOT = Path(__file__).resolve().parents[1]
FILTER_FILE = ROOT / "family-filter.js"
OUTPUT_FILE = ROOT / "dictionary-additions.js"

# Reported words and game-specific vocabulary are kept even when a source corpus
# does not contain or tag them.
FORCED_WORDS = {
    "boot", "boots", "crisscross", "cue", "diagonal", "diagonals", "dire",
    "due", "hair", "hairs", "jem", "lid", "neat", "neater", "neatest",
    "neatly", "swipe", "swiped", "swipes", "swiping", "wordburst",
    "zigzag", "zigzags",
}

PROPER_NOUN_TAGS = {"NNP", "NNPS"}


def parse_family_blocklist() -> set[str]:
    source = FILTER_FILE.read_text(encoding="utf-8")
    sections = re.findall(
        r"new Set\(`\s*(.*?)\s*`\.trim\(\)\.split",
        source,
        flags=re.DOTALL,
    )
    blocked: set[str] = set()
    for section in sections:
        blocked.update(re.findall(r"[a-z]+", section.lower()))

    # Also remove ordinary suffix forms of blocked roots without using unsafe
    # substring matching. This does not catch innocent words such as "analysis"
    # or "class" merely because they contain the same letters.
    suffixes = ("s", "es", "ed", "ing", "er", "ers", "y", "ly")
    expanded = set(blocked)
    for word in blocked:
        expanded.update(word + suffix for suffix in suffixes)
    return expanded


def parse_spelling_counts(path: Path) -> dict[str, int]:
    counts: dict[str, int] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(";"):
            continue
        try:
            word, count = line.rsplit(" ", 1)
            counts[word.lower()] = int(count)
        except ValueError:
            continue
    return counts


def parse_lexicon(path: Path) -> dict[str, list[str]]:
    tags: dict[str, list[str]] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(";"):
            continue
        parts = line.split()
        if len(parts) >= 2:
            tags[parts[0].lower()] = parts[1:]
    return tags


def wrap_words(words: list[str], width: int = 108) -> str:
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if current and len(candidate) > width:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return "\n".join(lines)


def main() -> None:
    try:
        import textblob  # type: ignore
    except ImportError as exc:
        raise SystemExit(
            f"Install textblob=={TEXTBLOB_VERSION} before running this builder"
        ) from exc

    package_root = Path(textblob.__file__).resolve().parent / "en"
    spelling_path = package_root / "en-spelling.txt"
    lexicon_path = package_root / "en-lexicon.txt"
    if not spelling_path.exists() or not lexicon_path.exists():
        raise SystemExit("TextBlob English dictionary source files were not found")

    counts = parse_spelling_counts(spelling_path)
    lexicon = parse_lexicon(lexicon_path)
    blocked = parse_family_blocklist()

    words: set[str] = set()
    for word, count in counts.items():
        if count < 1 or not re.fullmatch(r"[a-z]+", word):
            continue
        if not 3 <= len(word) <= 20 or word in blocked:
            continue
        tags = lexicon.get(word, [])
        # Requiring a normal-prose part-of-speech tag removes most character
        # names and place names from the book-derived spelling corpus.
        if not tags or not any(tag not in PROPER_NOUN_TAGS for tag in tags):
            continue
        words.add(word)

    words.update(word for word in FORCED_WORDS if word not in blocked)
    ordered_words = sorted(words)
    word_data = wrap_words(ordered_words)

    output = f"""'use strict';

// AUTO-GENERATED by scripts/build_dictionary.py. Do not edit this word data by hand.
// Source: TextBlob {TEXTBLOB_VERSION} English spelling corpus + non-proper POS filtering.
// The family filter is applied both while building and again in the browser.
(() => {{
  const bundledWords = `
{word_data}
`.trim().split(/\\s+/);

  let added = 0;
  for (const word of bundledWords) {{
    if (word.length >= 3 && isFamilySafe(word) && !dictionary.has(word)) {{
      dictionary.add(word);
      added += 1;
    }}
  }}

  if (added && typeof markDictionaryUpdated === 'function') markDictionaryUpdated();
  window.WORDBURST_DICTIONARY_SIZE = dictionary.size;
}})();
"""
    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"Wrote {{len(ordered_words):,}} bundled words to {{OUTPUT_FILE.name}}")


if __name__ == "__main__":
    main()
